/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int DROP_TABLE = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int INSERT_INTO = 12;
  /** RegularExpression Id. */
  int DELETE_FROM = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int SHOW_TABLES = 15;
  /** RegularExpression Id. */
  int NOT_NULL = 16;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 17;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 18;
  /** RegularExpression Id. */
  int REFERENCES = 19;
  /** RegularExpression Id. */
  int AS = 20;
  /** RegularExpression Id. */
  int FROM = 21;
  /** RegularExpression Id. */
  int WHERE = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int IS = 26;
  /** RegularExpression Id. */
  int NULL = 27;
  /** RegularExpression Id. */
  int VALUES = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int LEFT_PAREN = 30;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 31;
  /** RegularExpression Id. */
  int COMMA = 32;
  /** RegularExpression Id. */
  int PERIOD = 33;
  /** RegularExpression Id. */
  int GREATER = 34;
  /** RegularExpression Id. */
  int LESS = 35;
  /** RegularExpression Id. */
  int EQUAL = 36;
  /** RegularExpression Id. */
  int STAR = 37;
  /** RegularExpression Id. */
  int UNDERSCORE = 38;
  /** RegularExpression Id. */
  int UPPERSCORE = 39;
  /** RegularExpression Id. */
  int CHAR_STRING = 40;
  /** RegularExpression Id. */
  int INT_VALUE = 41;
  /** RegularExpression Id. */
  int SIGN = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;
  /** RegularExpression Id. */
  int NNNN = 44;
  /** RegularExpression Id. */
  int NN = 45;
  /** RegularExpression Id. */
  int DATE_VALUE = 46;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 47;
  /** RegularExpression Id. */
  int ALPHABET = 48;
  /** RegularExpression Id. */
  int GRE = 49;
  /** RegularExpression Id. */
  int LE = 50;
  /** RegularExpression Id. */
  int NE = 51;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 52;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 53;
  /** RegularExpression Id. */
  int QUOTE_STATE1 = 54;
  /** RegularExpression Id. */
  int QUOTE_DEFAULT = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STATE1 = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"drop table\"",
    "\"desc\"",
    "\"insert into\"",
    "\"delete from\"",
    "\"select\"",
    "\"show tables\"",
    "\"not null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\"as\"",
    "\"from\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"is\"",
    "\"null\"",
    "\"values\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"*\"",
    "\"_\"",
    "\"-\"",
    "<CHAR_STRING>",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<NNNN>",
    "<NN>",
    "<DATE_VALUE>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "<NON_QUOTE_CHARACTER>",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "\"\\\'\"",
    "\"\\\'\"",
  };

}
